/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_spi.h"
#include "fsl_lpuart.h"
#include "fsl_clock.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* BOARD_InitPeripherals defines for SPI0 */
/* Definition of peripheral ID */
#define SF_SPI_PERIPHERAL SPI0
/* Definition of the clock source */
#define SF_SPI_CLOCK_SOURCE SPI0_CLK_SRC
/* Definition of the clock source frequency */
#define SF_SPI_CLK_FREQ CLOCK_GetFreq(SF_SPI_CLOCK_SOURCE)
/* BOARD_InitPeripherals defines for SPI1 */
/* Definition of peripheral ID */
#define SENS_SPI_PERIPHERAL SPI1
/* Definition of the clock source */
#define SENS_SPI_CLOCK_SOURCE SPI1_CLK_SRC
/* Definition of the clock source frequency */
#define SENS_SPI_CLK_FREQ CLOCK_GetFreq(SENS_SPI_CLOCK_SOURCE)
/* Definition of peripheral ID */
#define LPUART0_PERIPHERAL LPUART0
/* Definition of the clock source frequency */
#define LPUART0_CLOCK_SOURCE 48000000UL

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const spi_master_config_t SF_SPI_config;
extern const spi_master_config_t SENS_SPI_config;
extern const lpuart_config_t LPUART0_config;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
