/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_LPUART0RXSRC_LPUART_RX 0x00u /*!<@brief LPUART0 Receive Data Source Select: LPUART_RX pin */
#define SOPT5_LPUART0TXSRC_LPUART_TX 0x00u /*!<@brief LPUART0 Transmit Data Source Select: LPUART0_TX pin */

/*! @name PORTC5 (number 54), SF_SCK
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SF_SCK_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SF_SCK_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SF_SCK_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTC6 (number 55), SF_MOSI
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SF_MOSI_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SF_MOSI_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SF_MOSI_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTC7 (number 56), SF_MISO
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SF_MISO_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SF_MISO_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SF_MISO_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTC4 (number 53), SF_CS
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SF_CS_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_SF_CS_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SF_CS_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SF_CS_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SF_CS_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SF_CS_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTC20 (number 49), SF_ACK
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SF_ACK_FGPIO FGPIOC              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_SF_ACK_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SF_ACK_GPIO_PIN_MASK (1U << 20U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SF_ACK_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SF_ACK_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SF_ACK_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTC1 (number 44), SF_RESET
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SF_RESET_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_SF_RESET_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SF_RESET_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SF_RESET_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SF_RESET_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SF_RESET_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTE29 (number 17), ADC_BATT
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ADC_BATT_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ADC_BATT_PIN 29U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ADC_BATT_PIN_MASK (1U << 29U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTD4 (number 61), SENS_CS
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SENS_CS_FGPIO FGPIOD             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_SENS_CS_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SENS_CS_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SENS_CS_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SENS_CS_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SENS_CS_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTD5 (number 62), SENS_SCK
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SENS_SCK_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SENS_SCK_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SENS_SCK_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTD6 (number 63), SENS_MOSI
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SENS_MOSI_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SENS_MOSI_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SENS_MOSI_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTD7 (number 64), SENS_MISO
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SENS_MISO_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SENS_MISO_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SENS_MISO_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTD3 (number 60), GNSS_FIX
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_GNSS_FIX_FGPIO FGPIOD             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_GNSS_FIX_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_GNSS_FIX_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_GNSS_FIX_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_GNSS_FIX_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_GNSS_FIX_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTB18 (number 41), GNSS_RESET
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_GNSS_RESET_FGPIO FGPIOB              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_GNSS_RESET_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_GNSS_RESET_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_GNSS_RESET_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_GNSS_RESET_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_GNSS_RESET_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORTC22 (number 51), GNSS_WU
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_GNSS_WU_FGPIO FGPIOC              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_GNSS_WU_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_GNSS_WU_GPIO_PIN_MASK (1U << 22U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_GNSS_WU_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_GNSS_WU_PIN 22U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_GNSS_WU_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
