/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v13.1
processor: K32L2B21xxxxA
package_id: K32L2B21VLH0A
mcu_data: ksdk2_0
processor_version: 13.0.1
pin_labels:
- {pin_num: '62', pin_signal: LCD_P45/ADC0_SE6b/PTD5/SPI1_SCK/UART2_TX/TPM0_CH5/FXIO0_D5, label: SENS_SCK, identifier: SF_SCK;SENS_SCK}
- {pin_num: '63', pin_signal: LCD_P46/ADC0_SE7b/PTD6/LLWU_P15/SPI1_MOSI/LPUART0_RX/SPI1_MISO/FXIO0_D6, label: SENS_MOSI, identifier: SF_MOSI;SENS_MOSI}
- {pin_num: '64', pin_signal: LCD_P47/PTD7/SPI1_MISO/LPUART0_TX/SPI1_MOSI/FXIO0_D7, label: SENS_MISO, identifier: SF_MISO;SENS_MISO}
- {pin_num: '61', pin_signal: LCD_P44/PTD4/LLWU_P14/SPI1_SS/UART2_RX/TPM0_CH4/FXIO0_D4, label: SENS_CS, identifier: SF_CS;SENS_CS}
- {pin_num: '49', pin_signal: VLL2/LCD_P4/PTC20, label: SF_ACK, identifier: SF_ACK}
- {pin_num: '54', pin_signal: LCD_P25/PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/CMP0_OUT, label: SF_SCK, identifier: SF_SCK}
- {pin_num: '55', pin_signal: LCD_P26/CMP0_IN0/PTC6/LLWU_P10/SPI0_MOSI/EXTRG_IN/SPI0_MISO, label: SF_MOSI, identifier: SF_MOSI}
- {pin_num: '56', pin_signal: LCD_P27/CMP0_IN1/PTC7/SPI0_MISO/USB_SOF_OUT/SPI0_MOSI, label: SF_MISO, identifier: SF_MISO}
- {pin_num: '53', pin_signal: LCD_P24/PTC4/LLWU_P8/SPI0_SS/LPUART1_TX/TPM0_CH3, label: SF_CS, identifier: SF_CS}
- {pin_num: '44', pin_signal: LCD_P21/ADC0_SE15/PTC1/LLWU_P6/RTC_CLKIN/I2C1_SCL/TPM0_CH0, label: SF_RESET, identifier: SF_RESET}
- {pin_num: '17', pin_signal: CMP0_IN5/ADC0_SE4b/PTE29/TPM0_CH2/TPM_CLKIN0, label: ADC_BATT, identifier: ADC_BATT}
- {pin_num: '60', pin_signal: LCD_P43/PTD3/SPI0_MISO/UART2_TX/TPM0_CH3/SPI0_MOSI/FXIO0_D3, label: GNSS_FIX, identifier: GNSS_FIX}
- {pin_num: '41', pin_signal: LCD_P14/PTB18/TPM2_CH0, label: GNSS_RESET, identifier: GNSS_RESET}
- {pin_num: '51', pin_signal: VCAP2/LCD_P6/PTC22, label: GNSS_WU, identifier: GNSS_WU}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '54', peripheral: SPI0, signal: SCK, pin_signal: LCD_P25/PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/CMP0_OUT}
  - {pin_num: '55', peripheral: SPI0, signal: MOSI, pin_signal: LCD_P26/CMP0_IN0/PTC6/LLWU_P10/SPI0_MOSI/EXTRG_IN/SPI0_MISO}
  - {pin_num: '56', peripheral: SPI0, signal: MISO, pin_signal: LCD_P27/CMP0_IN1/PTC7/SPI0_MISO/USB_SOF_OUT/SPI0_MOSI}
  - {pin_num: '53', peripheral: GPIOC, signal: 'GPIO, 4', pin_signal: LCD_P24/PTC4/LLWU_P8/SPI0_SS/LPUART1_TX/TPM0_CH3, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '49', peripheral: GPIOC, signal: 'GPIO, 20', pin_signal: VLL2/LCD_P4/PTC20, direction: INPUT}
  - {pin_num: '44', peripheral: GPIOC, signal: 'GPIO, 1', pin_signal: LCD_P21/ADC0_SE15/PTC1/LLWU_P6/RTC_CLKIN/I2C1_SCL/TPM0_CH0, direction: OUTPUT, gpio_init_state: 'true',
    drive_strength: low, pull_enable: enable}
  - {pin_num: '17', peripheral: ADC0, signal: 'SE, 4b', pin_signal: CMP0_IN5/ADC0_SE4b/PTE29/TPM0_CH2/TPM_CLKIN0}
  - {pin_num: '61', peripheral: GPIOD, signal: 'GPIO, 4', pin_signal: LCD_P44/PTD4/LLWU_P14/SPI1_SS/UART2_RX/TPM0_CH4/FXIO0_D4, identifier: SENS_CS, direction: OUTPUT,
    gpio_init_state: 'true'}
  - {pin_num: '62', peripheral: SPI1, signal: SCK, pin_signal: LCD_P45/ADC0_SE6b/PTD5/SPI1_SCK/UART2_TX/TPM0_CH5/FXIO0_D5, identifier: SENS_SCK, direction: OUTPUT}
  - {pin_num: '63', peripheral: SPI1, signal: MOSI, pin_signal: LCD_P46/ADC0_SE7b/PTD6/LLWU_P15/SPI1_MOSI/LPUART0_RX/SPI1_MISO/FXIO0_D6, identifier: SENS_MOSI, direction: OUTPUT}
  - {pin_num: '64', peripheral: SPI1, signal: MISO, pin_signal: LCD_P47/PTD7/SPI1_MISO/LPUART0_TX/SPI1_MOSI/FXIO0_D7, identifier: SENS_MISO, direction: INPUT}
  - {pin_num: '39', peripheral: LPUART0, signal: RX, pin_signal: LCD_P12/PTB16/SPI1_MOSI/LPUART0_RX/TPM_CLKIN0/SPI1_MISO}
  - {pin_num: '40', peripheral: LPUART0, signal: TX, pin_signal: LCD_P13/PTB17/SPI1_MISO/LPUART0_TX/TPM_CLKIN1/SPI1_MOSI}
  - {pin_num: '60', peripheral: GPIOD, signal: 'GPIO, 3', pin_signal: LCD_P43/PTD3/SPI0_MISO/UART2_TX/TPM0_CH3/SPI0_MOSI/FXIO0_D3, direction: INPUT}
  - {pin_num: '41', peripheral: GPIOB, signal: 'GPIO, 18', pin_signal: LCD_P14/PTB18/TPM2_CH0, direction: OUTPUT, gpio_init_state: 'true', pull_enable: enable}
  - {pin_num: '51', peripheral: GPIOC, signal: 'GPIO, 22', pin_signal: VCAP2/LCD_P6/PTC22, direction: OUTPUT, gpio_init_state: 'false'}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    gpio_pin_config_t GNSS_RESET_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTB18 (pin 41)  */
    GPIO_PinInit(BOARD_INITPINS_GNSS_RESET_GPIO, BOARD_INITPINS_GNSS_RESET_PIN, &GNSS_RESET_config);

    gpio_pin_config_t SF_RESET_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTC1 (pin 44)  */
    GPIO_PinInit(BOARD_INITPINS_SF_RESET_GPIO, BOARD_INITPINS_SF_RESET_PIN, &SF_RESET_config);

    gpio_pin_config_t SF_CS_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTC4 (pin 53)  */
    GPIO_PinInit(BOARD_INITPINS_SF_CS_GPIO, BOARD_INITPINS_SF_CS_PIN, &SF_CS_config);

    gpio_pin_config_t SF_ACK_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC20 (pin 49)  */
    GPIO_PinInit(BOARD_INITPINS_SF_ACK_GPIO, BOARD_INITPINS_SF_ACK_PIN, &SF_ACK_config);

    gpio_pin_config_t GNSS_WU_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC22 (pin 51)  */
    GPIO_PinInit(BOARD_INITPINS_GNSS_WU_GPIO, BOARD_INITPINS_GNSS_WU_PIN, &GNSS_WU_config);

    gpio_pin_config_t GNSS_FIX_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD3 (pin 60)  */
    GPIO_PinInit(BOARD_INITPINS_GNSS_FIX_GPIO, BOARD_INITPINS_GNSS_FIX_PIN, &GNSS_FIX_config);

    gpio_pin_config_t SENS_CS_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTD4 (pin 61)  */
    GPIO_PinInit(BOARD_INITPINS_SENS_CS_GPIO, BOARD_INITPINS_SENS_CS_PIN, &SENS_CS_config);

    /* PORTB16 (pin 39) is configured as LPUART0_RX */
    PORT_SetPinMux(PORTB, 16U, kPORT_MuxAlt3);

    /* PORTB17 (pin 40) is configured as LPUART0_TX */
    PORT_SetPinMux(PORTB, 17U, kPORT_MuxAlt3);

    /* PORTB18 (pin 41) is configured as PTB18 */
    PORT_SetPinMux(BOARD_INITPINS_GNSS_RESET_PORT, BOARD_INITPINS_GNSS_RESET_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[18] = ((PORTB->PCR[18] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Enable: Internal pullup or pulldown resistor is enabled on the corresponding pin. */
                      | (uint32_t)(PORT_PCR_PE_MASK));

    /* PORTC1 (pin 44) is configured as PTC1 */
    PORT_SetPinMux(BOARD_INITPINS_SF_RESET_PORT, BOARD_INITPINS_SF_RESET_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[1] = ((PORTC->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Enable: Internal pullup or pulldown resistor is enabled on the corresponding pin. */
                     | (uint32_t)(PORT_PCR_PE_MASK));

    /* PORTC20 (pin 49) is configured as PTC20 */
    PORT_SetPinMux(BOARD_INITPINS_SF_ACK_PORT, BOARD_INITPINS_SF_ACK_PIN, kPORT_MuxAsGpio);

    /* PORTC22 (pin 51) is configured as PTC22 */
    PORT_SetPinMux(BOARD_INITPINS_GNSS_WU_PORT, BOARD_INITPINS_GNSS_WU_PIN, kPORT_MuxAsGpio);

    /* PORTC4 (pin 53) is configured as PTC4 */
    PORT_SetPinMux(BOARD_INITPINS_SF_CS_PORT, BOARD_INITPINS_SF_CS_PIN, kPORT_MuxAsGpio);

    /* PORTC5 (pin 54) is configured as SPI0_SCK */
    PORT_SetPinMux(BOARD_INITPINS_SF_SCK_PORT, BOARD_INITPINS_SF_SCK_PIN, kPORT_MuxAlt2);

    /* PORTC6 (pin 55) is configured as SPI0_MOSI */
    PORT_SetPinMux(BOARD_INITPINS_SF_MOSI_PORT, BOARD_INITPINS_SF_MOSI_PIN, kPORT_MuxAlt2);

    /* PORTC7 (pin 56) is configured as SPI0_MISO */
    PORT_SetPinMux(BOARD_INITPINS_SF_MISO_PORT, BOARD_INITPINS_SF_MISO_PIN, kPORT_MuxAlt2);

    /* PORTD3 (pin 60) is configured as PTD3 */
    PORT_SetPinMux(BOARD_INITPINS_GNSS_FIX_PORT, BOARD_INITPINS_GNSS_FIX_PIN, kPORT_MuxAsGpio);

    /* PORTD4 (pin 61) is configured as PTD4 */
    PORT_SetPinMux(BOARD_INITPINS_SENS_CS_PORT, BOARD_INITPINS_SENS_CS_PIN, kPORT_MuxAsGpio);

    /* PORTD5 (pin 62) is configured as SPI1_SCK */
    PORT_SetPinMux(BOARD_INITPINS_SENS_SCK_PORT, BOARD_INITPINS_SENS_SCK_PIN, kPORT_MuxAlt2);

    /* PORTD6 (pin 63) is configured as SPI1_MOSI */
    PORT_SetPinMux(BOARD_INITPINS_SENS_MOSI_PORT, BOARD_INITPINS_SENS_MOSI_PIN, kPORT_MuxAlt2);

    /* PORTD7 (pin 64) is configured as SPI1_MISO */
    PORT_SetPinMux(BOARD_INITPINS_SENS_MISO_PORT, BOARD_INITPINS_SENS_MISO_PIN, kPORT_MuxAlt2);

    /* PORTE29 (pin 17) is configured as ADC0_SE4b */
    PORT_SetPinMux(BOARD_INITPINS_ADC_BATT_PORT, BOARD_INITPINS_ADC_BATT_PIN, kPORT_PinDisabledOrAnalog);

    SIM->SOPT5 = ((SIM->SOPT5 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT5_LPUART0TXSRC_MASK | SIM_SOPT5_LPUART0RXSRC_MASK)))

                  /* LPUART0 Transmit Data Source Select: LPUART0_TX pin. */
                  | SIM_SOPT5_LPUART0TXSRC(SOPT5_LPUART0TXSRC_LPUART_TX)

                  /* LPUART0 Receive Data Source Select: LPUART_RX pin. */
                  | SIM_SOPT5_LPUART0RXSRC(SOPT5_LPUART0RXSRC_LPUART_RX));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
