/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_LPUART0RXSRC_LPUART_RX 0x00u /*!<@brief LPUART0 Receive Data Source Select: LPUART_RX pin */
#define SOPT5_LPUART0TXSRC_LPUART_TX 0x00u /*!<@brief LPUART0 Transmit Data Source Select: LPUART0_TX pin */

/*! @name PORTB17 (number 40), GNSS_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_GNSS_TX_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_GNSS_TX_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_GNSS_TX_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTB16 (number 39), GNSS_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_GNSS_RX_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_GNSS_RX_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_GNSS_RX_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTB18 (number 41), GNSS_RESET
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_GNSS_RESET_FGPIO FGPIOB              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_GNSS_RESET_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_GNSS_RESET_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_GNSS_RESET_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_GNSS_RESET_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_GNSS_RESET_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORTD3 (number 60), GNSS_FIX
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_GNSS_FIX_FGPIO FGPIOD             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_GNSS_FIX_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_GNSS_FIX_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_GNSS_FIX_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_GNSS_FIX_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_GNSS_FIX_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTC22 (number 51), GNSS_WU
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_GNSS_WU_FGPIO FGPIOC              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_GNSS_WU_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_GNSS_WU_GPIO_PIN_MASK (1U << 22U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_GNSS_WU_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_GNSS_WU_PIN 22U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_GNSS_WU_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
