/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v13.1
processor: K32L2B21xxxxA
package_id: K32L2B21VLH0A
mcu_data: ksdk2_0
processor_version: 13.0.1
pin_labels:
- {pin_num: '41', pin_signal: LCD_P14/PTB18/TPM2_CH0, label: GNSS_RESET, identifier: GNSS_RESET}
- {pin_num: '60', pin_signal: LCD_P43/PTD3/SPI0_MISO/UART2_TX/TPM0_CH3/SPI0_MOSI/FXIO0_D3, label: GNSS_FIX, identifier: GNSS_FIX}
- {pin_num: '51', pin_signal: VCAP2/LCD_P6/PTC22, label: GNSS_WU, identifier: GNSS_WU}
- {pin_num: '40', pin_signal: LCD_P13/PTB17/SPI1_MISO/LPUART0_TX/TPM_CLKIN1/SPI1_MOSI, label: GNSS_TX, identifier: GNSS_TX}
- {pin_num: '39', pin_signal: LCD_P12/PTB16/SPI1_MOSI/LPUART0_RX/TPM_CLKIN0/SPI1_MISO, label: GNSS_RX, identifier: GNSS_RX}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '40', peripheral: LPUART0, signal: TX, pin_signal: LCD_P13/PTB17/SPI1_MISO/LPUART0_TX/TPM_CLKIN1/SPI1_MOSI, direction: OUTPUT}
  - {pin_num: '39', peripheral: LPUART0, signal: RX, pin_signal: LCD_P12/PTB16/SPI1_MOSI/LPUART0_RX/TPM_CLKIN0/SPI1_MISO}
  - {pin_num: '41', peripheral: GPIOB, signal: 'GPIO, 18', pin_signal: LCD_P14/PTB18/TPM2_CH0, direction: OUTPUT, gpio_init_state: 'true', pull_enable: enable}
  - {pin_num: '60', peripheral: GPIOD, signal: 'GPIO, 3', pin_signal: LCD_P43/PTD3/SPI0_MISO/UART2_TX/TPM0_CH3/SPI0_MOSI/FXIO0_D3, direction: INPUT}
  - {pin_num: '51', peripheral: GPIOC, signal: 'GPIO, 22', pin_signal: VCAP2/LCD_P6/PTC22, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);

    gpio_pin_config_t GNSS_RESET_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTB18 (pin 41)  */
    GPIO_PinInit(BOARD_INITPINS_GNSS_RESET_GPIO, BOARD_INITPINS_GNSS_RESET_PIN, &GNSS_RESET_config);

    gpio_pin_config_t GNSS_WU_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC22 (pin 51)  */
    GPIO_PinInit(BOARD_INITPINS_GNSS_WU_GPIO, BOARD_INITPINS_GNSS_WU_PIN, &GNSS_WU_config);

    gpio_pin_config_t GNSS_FIX_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD3 (pin 60)  */
    GPIO_PinInit(BOARD_INITPINS_GNSS_FIX_GPIO, BOARD_INITPINS_GNSS_FIX_PIN, &GNSS_FIX_config);

    /* PORTB16 (pin 39) is configured as LPUART0_RX */
    PORT_SetPinMux(BOARD_INITPINS_GNSS_RX_PORT, BOARD_INITPINS_GNSS_RX_PIN, kPORT_MuxAlt3);

    /* PORTB17 (pin 40) is configured as LPUART0_TX */
    PORT_SetPinMux(BOARD_INITPINS_GNSS_TX_PORT, BOARD_INITPINS_GNSS_TX_PIN, kPORT_MuxAlt3);

    /* PORTB18 (pin 41) is configured as PTB18 */
    PORT_SetPinMux(BOARD_INITPINS_GNSS_RESET_PORT, BOARD_INITPINS_GNSS_RESET_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[18] = ((PORTB->PCR[18] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Enable: Internal pullup or pulldown resistor is enabled on the corresponding pin. */
                      | (uint32_t)(PORT_PCR_PE_MASK));

    /* PORTC22 (pin 51) is configured as PTC22 */
    PORT_SetPinMux(BOARD_INITPINS_GNSS_WU_PORT, BOARD_INITPINS_GNSS_WU_PIN, kPORT_MuxAsGpio);

    /* PORTD3 (pin 60) is configured as PTD3 */
    PORT_SetPinMux(BOARD_INITPINS_GNSS_FIX_PORT, BOARD_INITPINS_GNSS_FIX_PIN, kPORT_MuxAsGpio);

    SIM->SOPT5 = ((SIM->SOPT5 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT5_LPUART0TXSRC_MASK | SIM_SOPT5_LPUART0RXSRC_MASK)))

                  /* LPUART0 Transmit Data Source Select: LPUART0_TX pin. */
                  | SIM_SOPT5_LPUART0TXSRC(SOPT5_LPUART0TXSRC_LPUART_TX)

                  /* LPUART0 Receive Data Source Select: LPUART_RX pin. */
                  | SIM_SOPT5_LPUART0RXSRC(SOPT5_LPUART0RXSRC_LPUART_RX));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
